[code]
editor = "nvim"
lang = "python3"
edit_code_marker = true
start_marker = "solution_start"
end_marker = "solution_end"
# if include problem description
comment_problem_desc = true
# comment syntax
comment_leading = "#"
test = true
inject_before = ["from typing import List"]

[cookies]
csrf = ""
session = ""
site = "leetcode.com"

[storage]
root = "~/.leetcode"
cache = "Problems"
code = "code"
scripts = "scripts"
