[code]
editor = "nvim"
lang = "python"
edit_code_marker = true
start_marker = "solution_start"
end_marker = "solution_end"
# if include problem description
comment_problem_desc = true
# comment syntax
comment_leading = "#"
test = true

[cookies]
csrf = ""
session = ""
site = "leetcode.com"

[storage]
cache = "Problems"
code = "code"
root = "~/.leetcode"
scripts = "scripts"
